### PR TITLE
Inline styles with refactored CSS and a more refreshed codebase

### PR DESCRIPTION
**Pull request by retrixe**
# List of what this pull request aims to cover:
- [x] Enable ES Module support by switching to Rollup.
- [x] Move index.js inside src and remove index.html
- [x] Remove Webpack.
- [x] Remove prop-types.
- [x] Reduce unnecessary dependencies.
- [x] Bring Flow support with at least 75%, recommended 80% coverage per file as per flow-ide (these values may be super inaccurate).
- [x] Move to inline styles with Aphrodite, more specifically a faster and better flavor of Aphrodite named `aphrodite-jss`. (this excludes RSGProgressBar and RSGCheckbox)
- [x] Wishes to undo the wreck that is the `css` folder.
- [x] ~Write styles for RSGCheckbox and RSGProgressBar using a new, in-house tool named `protoSASS`  to manually inject styling within the application.~
- [x] Finishes the rewritten codebase.

# Extraneous additions:
- Removal of `/tips` and GitHub Pages (credits: @Radi123).
- Changes to RSGCheckbox's API (credits:  @Radi123).
- Adds an example of RSGComponents using, temporarily, development versions of RSGComponents, Meteor and some other stuff (credits: @retrixe).
- Add Code Climate. Yus! (credits: @retrixe)

# What this pull request wishes to bring to the table in the future:
- Bring tests (now require installation of jest with `--save-dev` or `-D` for yarn).
- v3.0 and more refreshes on the codebase.

# Changes require major versioning bump to rsg-components due to:
- Defaults and styles of most components possibly changed, although coordination was done to avoid this. Should not have any effect on the look if everything goes right, if it does, patches will be pushed. It is preferable to keep this as a new major release due to this.
- ES Module support introduced and Webpack is being deprecated for Rollup (status unclear).
- Move to inline styles which deprecates many CSS-based features.
- Wishes to undo the wreck that is the `css` folder.

### CODE REVIEW

**Comment by ibujs** [comment]
Progress per component:
- RSGBox
- [x] Inline styled.
- [ ] COMPLETE Flow support.
- RSGButton
- [x] Inline styled.
- [ ] COMPLETE Flow support.
- RSGCheckbox
- [ ] Inline styled.
- [ ] COMPLETE Flow support.
- RSGFormBasic
- [ ] Inline styled.
- [ ] COMPLETE Flow support.
- RSGLabel
- [ ] Inline styled.
- [ ] COMPLETE Flow support.
- RSGProgressBar
- [ ] Inline styled.
- [ ] COMPLETE Flow support.
- RSGTransition
- [ ] Inline styled.
- [ ] COMPLETE Flow support.

**Comment by ibujs** [comment]
@Radi123 *coldly* what remains the purpose of a checkbox without handleClicks? also, it definitely should not have state (discussed on Slack).

**Comment by retrixe** [comment]
I've fixed RSGCheckbox and am pushing the changes. I also switched to [Fela](fela.js.org) with `react-fela` and I think it's excellent :stuck_out_tongue: 
so yea. I also removed Aphrodite.

**Comment by retrixe** [comment]
LGTM. Waiting for @Radi123 to approve these so I can merge this in.

**Comment by retrixe** [comment]
Merged.
A small step for man, a giant leap for mankind.

**Comment by Radi123** [comment]
@retrixe yeah

**Comment by retrixe** [comment]
Will be locking conversation to contributors and team members. If there are any issues with the 3.x release branch, file issues under the `Release: 3.x` tag.

**Pull request merged**
