### PR TITLE
The new component - Clock

### PR DESCRIPTION
**Pull request by radi-cho**
## List of what this pull request aims to cover.
- [x] Add the new component - Clock
- [x] Write new examples
- [ ] Write wiki and blog posts

### What's inside:
- Resizable SVG clock
- When the size is too small text clock

## Changes require major versioning bump to rsg-components due to:
- Adding new component

### CODE REVIEW

**Comment by radi-cho** [comment]
Ok. There was conflicts. Tried to resolve them but there was another problems. I didn't created new mess. Just closed the last PR #9, fix everything and open this.

**Comment by retrixe** [comment]
why. do. you. do. this.
#9 was.. perfectly fine. you don't have to resolve conflicts or ANYTHING. Why do you do this.
Conflicts are something I can resolve. they happen in every OSS project. stop making a big deal of it and don't do this again. yes, i'm getting pissed now, stop playing with Git.
master will always have work done on it and the solution is not to create more PRs but let the person merging it deal with it. STOP RESOLVING THESE STUPID ASS CONFLICTS.
Or repos like zeit/next.js will have PR numbers like #99966669

**Comment by radi-cho** [comment]
Yes, you're right.
Can't understand why you closed this but whatever... you're right.

**Comment by radi-cho** [comment]
What I did yesterday:
1. Merged master to clock branch, because there was bugs fixed on `master`, but not on `clock`.
2. Pushed a lot of clock improvements - Now the clock can be smaller, the time hands are also resizable, the colors was changed (now they're much better) and now the developers can add styles to clock's div.
3. Added new example... - @retrixe - Please review it, if you don't like it or there's a problem revert the commit (https://github.com/RSG-Group/rsg-components/pull/10/commits/a21633ef1b18231f6c506e1c9b3d1cfbbcbd0bff)...

**Comment by retrixe** [comment]
LGTM. Must I remind you not to merge PRs yourself without express approval later on.

**Comment by radi-cho** [comment]
Oh, OK.... ....

**Pull request merged**
