### PR TITLE
New styles for RSGButton, Label and Box.

### PR DESCRIPTION
**Pull request by radi-cho**
## List of what this pull request aims to cover.
- [x] Add new styles and features to existing components.
- [ ] ~~Add new examples for the changed components.~~
___
#### New styles applied to:
- [x] `RSGButton`
- [x] `RSGLabel`
- [x] `RSGBox`

## Changes require major versioning bump to rsg-components due to:
- Change of styling in certain components.
- Change to their respective APIs.

### CODE REVIEW

**Comment by Radi123** [comment]
This commit is actually copy of #4 It's because I merged #4 unintentionally... After that fixed the mess in the branches, but there isn't way to reopen or delete #4 and now we're here.

For earlier reviews, comments & others please read #4, too.

**Comment by retrixe** [comment]
Don't bump version numbers in PRs!

**Comment by retrixe** [comment]
I see you fixed some of my inefficiencies in RSGLabel, yes, I did make some mistakes but.. why did you replace it with something more inefficient? Instead of an arrow function, you could simply assign it to a string. I've done so in my new commit.

The wiki will need a rewrite of certain parts after this indeed.

**Comment by retrixe** [comment]
Oh wow, and your implementation didn't work either.

**Comment by radi-cho** [comment]
@retrixe OH, Yeah, sorry.

**Comment by retrixe** [comment]
Are you done with RSGLabel and Box?

There's a bug with RSGBox I'm filing so if this could be sorted out in this PR, would be great.

**Comment by retrixe** [comment]
DUDE! WHERE ARE ALL THE post-alpha.4 commits!
THEY'RE GONE!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by radi-cho** [comment]
@retrixe What????

**Comment by retrixe** [comment]
The standard code style and everything is gone from master and is now here..

**Comment by retrixe** [comment]
Any issues have been resolved via talks, progress continues.

**Comment by radi-cho** [comment]
@retrixe Please review the PR now

**Comment by radi-cho** [comment]
View this video: https://youtu.be/x2ziU3-cL44

**Pull request merged**
