### PR TITLE
Major refactors and cleaner code (see description)

### PR DESCRIPTION
**Pull request by ibujs**
## List of what this pull request aims to cover.
- [x] Add a LICENSE for legal usage.
- [x] Updated packages and moved to ES2015 and Webpack.
- [x] Added Mocha and Chai, with tests coming.
- [x] Added ESLint for linting.
- [x] Moved react and react-dom to peer deps. Fixed lots of deprecations.
- [x] Add prop-types.
- [x] Remove `docs` or do something about it.
- [x] Refactor prop names.
- [x] Clean and tidy up code with JSX.

## What this pull request wishes to bring to the table in the future:
- Static typing with `flow` to remove prop-types in the future.
- Write tests.
- Refactored CSS.

## Changes require major versioning bump to rsg-components due to:
- ~~ES Module support.~~ Not really, there may be issues with Webpack 2 and Rollup based projects using these components as of yet. I will enable this later.
- Removed breaking deprecations.
- Defaults of most components possibly changed, although coordination was done to avoid this. Should not have any effect on the look if everything goes right, if it does, patches will be pushed. It is preferable to keep this as a new major release due to this.
- React shifted to peer dependencies.
- React Fiber (aka the fresh codebase with a new architecture coming in React 16.0.0) support introduced. (Tests will keep running against React 15.5.4)

### CODE REVIEW

**Comment by ibujs** [comment]
## Do not merge the branch yet and do not bump the version.
## Please review the code now, though, @Radi123 because this is the last comment which changes code enough to require a review.
By tomorrow, this pull request should be complete (I need to sleep). Also, because there's nothing left for me to do. I require @Radi123 to comment here on what to do with `docs` for me to do something. I also request @Radi123 to make me a contributor on npm (my username on npm is ibujs).

I also spent 5 hours on this so a shout-out would be awesome :stuck_out_tongue:

**Comment by Radi123** [comment]
@ibujs Thank you for your time :smile: 
## Docs
I think in Slack you understand what to do with docs - delete the folder docs/. I shall improve them and push at rsg-group.github.io repo and website :+1:

**Comment by Radi123** [comment]
# Thank you, very much

**Comment by ibujs** [comment]
You may merge after code reviewing.

**Comment by ibujs** [comment]
Yus!

**Pull request merged**
